'use client';

import { useState } from 'react';
import Link from 'next/link';

interface FaqItem {
  q: string;
  a: string;
}

const HOME_FAQS: FaqItem[] = [
  {
    q: 'How does CBT RANK calculate my exam score?',
    a: 'CBT RANK parses the official HTML response sheet generated by TCS iON / DigiALM exam portals. It counts your correct answers, incorrect answers, unattempted questions, and automatically applies official exam negative marking (e.g. 0.25, 0.33, or 0.50 marks per wrong answer) to give you an exact raw score breakdown.'
  },
  {
    q: 'How is Shift Rank and Category Rank calculated?',
    a: 'Your shift rank is computed in real-time by comparing your raw score against all candidates who appeared in the exact same exam shift and date. Category rank compares your score against all candidates within your category (UR, OBC, EWS, SC, ST).'
  },
  {
    q: 'Is CBT RANK safe to use? Do I need to share my roll number or password?',
    a: 'CBT RANK is 100% secure. You never need to enter your exam password or personal login credentials. You only paste your public response sheet URL to compute your marks.'
  },
  {
    q: 'Which exams are supported on CBT RANK?',
    a: 'CBT RANK supports all major Indian government competitive examinations, including SSC (CGL, CHSL, MTS, GD, JE, CPO), Railway (RRB NTPC, Group D, ALP, Technician, Paramedical), State Selection Boards (OSSC, OSSSC, DSSSB, UPSSSC), and other central recruitment tests.'
  }
];

export default function HomeSeoContent() {
  const [openIndices, setOpenIndices] = useState<number[]>([]);

  const toggleFaq = (index: number) => {
    setOpenIndices((prev) =>
      prev.includes(index) ? prev.filter((i) => i !== index) : [...prev, index]
    );
  };

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: HOME_FAQS.map((item) => ({
      '@type': 'Question',
      name: item.q,
      acceptedAnswer: {
        '@type': 'Answer',
        text: item.a,
      },
    })),
  };

  return (
    <section className="home-seo-section" aria-label="About CBT Rank Platform">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      <style>{`
        .home-seo-container {
          margin-top: 48px;
          display: flex;
          flex-direction: column;
          gap: 36px;
        }
        .seo-card {
          background: #ffffff;
          border: 1px solid #e2e8f0;
          border-radius: 16px;
          padding: 28px;
          box-shadow: 0 4px 12px rgba(15, 23, 42, 0.03);
        }
        .seo-title {
          font-size: 1.35rem;
          font-weight: 800;
          color: #0f172a;
          margin-bottom: 12px;
          line-height: 1.3;
        }
        .seo-subtitle {
          font-size: 0.94rem;
          color: #475569;
          line-height: 1.65;
          margin-bottom: 20px;
        }
        .steps-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
          gap: 16px;
          margin-top: 16px;
        }
        .step-item {
          background: #f8fafc;
          border: 1px solid #e2e8f0;
          border-radius: 12px;
          padding: 18px;
          transition: transform 0.2s ease, border-color 0.2s ease;
        }
        .step-item:hover {
          transform: translateY(-2px);
          border-color: #93c5fd;
        }
        .step-badge {
          display: inline-block;
          font-size: 0.72rem;
          font-weight: 800;
          text-transform: uppercase;
          background: #eff6ff;
          color: #1d4ed8;
          padding: 3px 10px;
          border-radius: 999px;
          margin-bottom: 10px;
        }
        .step-heading {
          font-size: 1rem;
          font-weight: 700;
          color: #1e293b;
          margin-bottom: 6px;
        }
        .step-desc {
          font-size: 0.85rem;
          color: #64748b;
          line-height: 1.5;
        }
        .features-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
          gap: 16px;
          margin-top: 16px;
        }
        .feature-box {
          background: #f8fafc;
          border: 1px solid #e2e8f0;
          border-radius: 12px;
          padding: 16px;
        }
        .feature-icon {
          font-size: 1.5rem;
          margin-bottom: 8px;
        }
        .feature-title {
          font-size: 0.95rem;
          font-weight: 700;
          color: #0f172a;
          margin-bottom: 6px;
        }
        .feature-desc {
          font-size: 0.82rem;
          color: #64748b;
          line-height: 1.5;
        }
        .faq-list {
          display: flex;
          flex-direction: column;
          gap: 10px;
          margin-top: 16px;
        }
        .faq-item {
          background: #f8fafc;
          border: 1px solid #e2e8f0;
          border-radius: 12px;
          overflow: hidden;
          transition: border-color 0.2s ease;
        }
        .faq-item.is-open {
          border-color: #3b82f6;
          background: #ffffff;
        }
        .faq-toggle-btn {
          width: 100%;
          padding: 14px 18px;
          background: transparent;
          border: none;
          cursor: pointer;
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 12px;
          text-align: left;
        }
        .faq-q {
          font-size: 0.92rem;
          font-weight: 700;
          color: #1e293b;
          line-height: 1.4;
        }
        .faq-icon {
          font-size: 1.1rem;
          font-weight: 800;
          color: #64748b;
        }
        .faq-a {
          padding: 0 18px 14px 18px;
          font-size: 0.85rem;
          color: #475569;
          line-height: 1.6;
        }
        @media (max-width: 640px) {
          .seo-card { padding: 18px; }
          .seo-title { font-size: 1.15rem; }
        }
      `}</style>

      <div className="home-seo-container">
        {/* Section 1: About CBT Rank */}
        <article className="seo-card">
          <h2 className="seo-title">About CBT RANK - India&apos;s Trusted Answer Key &amp; Rank Predictor</h2>
          <p className="seo-subtitle">
            CBT RANK is a specialized evaluation platform designed for aspirants appearing in Computer Based Tests (CBT).
            Candidates can check their exact marks, analyze sectional accuracy, apply official negative marking, and predict their Shift Rank and Category Cutoff across major examinations including <strong>SSC CGL, CHSL, MTS, GD, RRB NTPC, Railway Group D, ALP, Technician</strong>, and state recruitment exams.
          </p>

          <div className="features-grid">
            <div className="feature-box">
              <div className="feature-icon">⚡</div>
              <h3 className="feature-title">Real-Time Shift Rank</h3>
              <p className="feature-desc">Compare your marks against all verified candidates from your specific exam shift.</p>
            </div>
            <div className="feature-box">
              <div className="feature-icon">🎯</div>
              <h3 className="feature-title">Accurate Negative Marking</h3>
              <p className="feature-desc">Automatic penalty deductions (1/3, 1/4, 0.25) calculated strictly per official notification.</p>
            </div>
            <div className="feature-box">
              <div className="feature-icon">📊</div>
              <h3 className="feature-title">Category Percentile</h3>
              <p className="feature-desc">Instant category rank analysis across UR, EWS, OBC, SC, and ST candidate pools.</p>
            </div>
            <div className="feature-box">
              <div className="feature-icon">🔒</div>
              <h3 className="feature-title">100% Safe &amp; Private</h3>
              <p className="feature-desc">No login or password needed. Simply paste your response sheet URL to compute scores.</p>
            </div>
          </div>
        </article>

        {/* Section 2: How it Works Guide */}
        <article className="seo-card">
          <h2 className="seo-title">How to Check Your Answer Key &amp; Calculate Rank</h2>
          <p className="seo-subtitle">
            Follow these 3 quick steps to verify your score and view live candidate standings:
          </p>

          <div className="steps-grid">
            <div className="step-item">
              <span className="step-badge">Step 1</span>
              <h3 className="step-heading">Copy Response Sheet URL</h3>
              <p className="step-desc">
                Log in to the official exam portal (DigiALM / TCS iON). Open your response sheet and copy the full page link from your browser&apos;s address bar.
              </p>
            </div>
            <div className="step-item">
              <span className="step-badge">Step 2</span>
              <h3 className="step-heading">Select Exam &amp; Category</h3>
              <p className="step-desc">
                Choose your exam from the list above (or use the universal calculator) and paste your link. Select your category, gender, and reservation details.
              </p>
            </div>
            <div className="step-item">
              <span className="step-badge">Step 3</span>
              <h3 className="step-heading">View Marks &amp; Live Rank</h3>
              <p className="step-desc">
                Get an instant breakdown of correct answers, negative deductions, net raw score, and your live percentile among all test-takers.
              </p>
            </div>
          </div>
        </article>

        {/* Section 3: Frequently Asked Questions (FAQ) */}
        <article className="seo-card">
          <h2 className="seo-title">Frequently Asked Questions</h2>
          <p className="seo-subtitle">
            Common questions regarding response sheet verification and rank prediction:
          </p>

          <div className="faq-list">
            {HOME_FAQS.map((faq, idx) => {
              const isOpen = openIndices.includes(idx);
              return (
                <div key={idx} className={`faq-item ${isOpen ? 'is-open' : ''}`}>
                  <button
                    type="button"
                    className="faq-toggle-btn"
                    onClick={() => toggleFaq(idx)}
                    aria-expanded={isOpen}
                  >
                    <span className="faq-q">{faq.q}</span>
                    <span className="faq-icon">{isOpen ? '−' : '+'}</span>
                  </button>
                  {isOpen && <p className="faq-a">{faq.a}</p>}
                </div>
              );
            })}
          </div>
        </article>
      </div>
    </section>
  );
}
